// Atenção: Não altere e não remova os valores {{entre chaves duplas}}.
// Eles podem, porém aparecer, em qualquer ordem e em qualquer lugar da respectiva string.
// Não coloque vírgula após o último elemento (pode acarretar erros em serviços externos)
var ejf_pt_BR = {
	"builder.message.delete": "Tem certeza que deseja apagar o item na posição {{position}}?",
	"builder.message.label.name.already.in.use": "Este nome já está sendo usado, por favor escolha outro.",
	"builder.message.label.name.cannot.be.numeric": "O nome do campo não pode conter apenas números.",
	"common.export.compound.field": "{{1st-level-label}}: {{2nd-lebel-label}}",
	"common.helptext": " <small>({{help-text}})</small>",
	"common.helptext.min.length.by.character": "min. caracteres: {{min}}",
	"common.helptext.max.length.by.character": "máx. caracteres: {{max}}",
	"common.helptext.min.length.by.word": "min. palavras: {{min}}",
	"common.helptext.max.length.by.word": "máx. palavras: {{max}}",
	"common.helptext.mandatory": "obrigatório",
	"common.helptext.separator": ", ",
	"common.label.new": "Novo {{field-type}} {{field-number}}",
	"common.value.no": "Não",
	"common.value.yes": "Sim",
	"item.file": "Arquivo",
	"item.file.helptext.filetypes": "tipos de arquivo: {{file-types}}",
	"item.file.helptext.filetypes.all": "todos",
	"item.file.helptext.maxsize": "tamanho máximo: {{size}} MB",
	"item.file.properties.filetypes": "Tipos de arquivo permitidos",
	"item.file.properties.maxsize": "Tamanho máximo (MB)",
	"item.file.vaule.uploaded.file": "Arquivo enviado",
	"item.textgroup": "Texto agrupado",
	"item.multiplechoice": "Escolha múltipla",
	"item.singlechoice": "Escolha simples",
	"item.singlechoice.value.null": ">> Selecione",
	"item.properties.customattribute": "Atributo personalizado",
	"item.properties.label": "Descrição",
	"item.properties.items": "Ítens",
	"item.properties.items.help": "Um por linha",
	"item.properties.mandatory": "Obrigatório",
	"item.number": "Número",
	"item.text": "Texto",
	"item.text.character.count": "{{chars}} caracteres",
	"item.text.properties.length.max": "Tamanho máximo",
	"item.text.properties.length.measure": "Restringir tamanho",
	"item.text.properties.length.measure.bycharacter": "Por caractere",
	"item.text.properties.length.measure.byword": "Por palavra",
	"item.text.properties.length.measure.no": "Não",
	"item.text.properties.length.min": "Tamanho mínimo",
	"item.text.properties.multiline": "Múltiplas linhas (área de texto)",
	"item.text.word.count": "{{words}} palavras",
	"validation.error.mandatory": "{{field-label}} é um campo obrigatório",
	"validation.error.please.select.one.option": "Por favor selecione ao menos uma opção",
	"validation.error.less.than.minimum.chars.accepted":"Menos caracteres do que o mínimo aceito",
	"validation.error.more.than.maximum.chars.accepted":"Mais caracteres do que o máximo aceito",
	"validation.error.less.than.minimum.words.accepted":"Menos palavras do que o mínimo aceito",
	"validation.error.more.than.maximum.words.accepted":"Mais palavras do que o máximo aceito",
	"validation.error.please.fill.all.fields":"Por favor preencha todos os campos"
};